name: Update Dataset Job

on:
  schedule:
      - cron: '0 23 * * *' 

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8  

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
            

      - name: Install dependencies
        run: |
          poetry install
        working-directory: ${{ github.workspace }}

      - name: Run the script
        run: poetry run python update_dataset.py
        working-directory: ${{ github.workspace }}
